os:
  - linux

sudo: required
dist: trusty

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential subversion libncurses5-dev zlib1g-dev gawk gcc-multilib flex git gettext libssl-dev unzip wget python2.7 time xz-utils
  - sudo apt-get purge file libmagic1 || true

  - wget -c -t 0 -T 15 "https://fossies.org/linux/misc/file-5.34.tar.gz"
  - tar xf file-5.34.tar.gz
  - cd file-5.34
  - ./configure --prefix=/usr --sysconfdir=/etc
  - make -j2
  - sudo make install
  - cd .. && rm -fr file-5.34

script:
  - ./scripts/feeds update -a
  - ./scripts/feeds install -a

  - cp -v ./my-config ./.config
  - cp -rv ./my-files ./files

  - cp -rv ./my-dl ./dl
  - make download

  - make -j2 V=s

  - echo
  - ls -lh ./bin/targets/ar71xx/generic/*.bin
  - echo
  - sha512sum ./bin/targets/ar71xx/generic/*.bin
  - echo
  - echo "******************** BEGIN openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-factory.bin | xz | base64 ********************"
  - xz -9 <./bin/targets/ar71xx/generic/openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-factory.bin | base64
  - echo "******************** END openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-factory.bin | xz | base64 ********************"
  - echo
  - echo "******************** BEGIN openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-sysupgrade.bin | xz | base64 ********************"
  - xz -9 <./bin/targets/ar71xx/generic/openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-sysupgrade.bin | base64
  - echo "******************** END openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-sysupgrade.bin | xz | base64 ********************"
  - echo
